### ISSUE TITLE
FATAL ERROR - MHN-Collector

### ISSUE THREAD

**Issue by qdm42** [threatstream/mhn#631] opened 2019-04-03 11:02 UTC
I'm trying to install MHN server but i have an error after running install.sh with supervisorctl status:
"mhn collector       FATAL      Exited too quickly (process log may have details)"

During the installation I see only one error : 
"geoip2 2.9.0 has requirement requests>=2.9, but you'll have requests 2.4.3 which is incompatible.
hpfeeds-logger 0.0.7.4 has requirement hpfeeds-threatstream==1.1, but you'll have hpfeeds-threatstream 1.0 which is incompatible."

I tried a "pip install" for requests and hpfeeds-threatstream, it works but after I had the same error while both packages should be in correct versions.

**Comment by phlipevil** [comment] 2019-04-03 11:28
Ok

**Comment by xsallowed** [comment] 2019-04-03 12:49
I am having same problem while installing hofeed-logger. I can see it saying that the connection with server is not successful


Best Regards~TahirNOTE: This message is sent from a handheld device therefore please excuse the brevity of this message.

On Wednesday, April 3, 2019, 12:28 PM, phlipevil <notifications@github.com> wrote:

Ok

**Comment by d1str0** [comment] 2019-04-04 02:12
Duplicate of #619

**Closed by d1str0** 2019-04-04 02:12 UTC

**Comment by qdm42** [comment] 2019-04-04 14:18
> Duplicate of #619

Exact, thanks !
Had seen this issue but I hadn't read everything
