### ISSUE TITLE
Deploy any script

### ISSUE THREAD

**Issue by j0rh3rp4** [threatstream/mhn#651] opened 2019-04-21 19:40 UTC
Hi, I'd tried to deploy every honeypots in ubuntu 14 and 16 (32 and 64 bits) with same error

++ curl -s -X POST -H 'Content-Type: application/json' -d '{
        "name": "honeypot1-amun",
        "hostname": "honeypot1",
        "deploy_key": "HO5d7q8a",
        "honeypot": "amun"
}' http://<<IP>>/api/sensor/
+++ python -c 'import json;obj=json.load(file("/tmp/deploy.json"));print obj["uuid"]'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
++ uuid=

Thanks

**Comment by f1r3walled** [comment] 2019-04-22 02:22
Duplicate of #650

**Comment by d1str0** [comment] 2019-04-22 22:53
#650 is now resolved.

**Closed by d1str0** 2019-04-22 22:53 UTC
