### ISSUE TITLE
Few errors after HTTPS deployed or free disk space?

### ISSUE THREAD

**Issue by br1877** [threatstream/mhn#427] opened 2017-07-03 14:47 UTC
I needed HTTPS on MHn server, so I had do it. After that I had want to clear MHN database and deployed new honeypots. But the problem is strange for me. Please look below and please, could somebody help me to resolve my errors?

```
geoloc                           RUNNING    pid 1521, uptime 0:19:44
honeymap                         RUNNING    pid 1545, uptime 0:19:42
hpfeeds-broker                   FATAL      Exited too quickly (process log may have details)
mhn-celery-beat                  RUNNING    pid 1506, uptime 0:19:44
mhn-celery-worker                FATAL      Exited too quickly (process log may have details)
mhn-collector                    FATAL      Exited too quickly (process log may have details)
mhn-uwsgi                        RUNNING    pid 1524, uptime 0:19:44
mnemosyne                        FATAL      Exited too quickly (process log may have details)
```

What is more, my VPS show me this:

```
command: df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            1,9G   12K  1,9G   1% /dev
tmpfs           386M  360K  386M   1% /run
/dev/vda1        20G   17G  2,2G  89% /
none            4,0K     0  4,0K   0% /sys/fs/cgroup
none            5,0M     0  5,0M   0% /run/lock
none            1,9G     0  1,9G   0% /run/shm
none            100M     0  100M   0% /run/user
```
But why the disk is fully in 89%? I had only two honeypots for a few days!

**Comment by Waseem-farooqui** [comment] 2017-07-03 14:56
Most the time the space is taken by the **mongo journals** you should check them if you want to free the space and then restart the mongodb service.Restarting mongo service will also resolve you fatal issue.

**Comment by br1877** [comment] 2017-07-03 15:02
I do not know what are you writing about. Maybe about this follow? https://github.com/threatstream/mhn/wiki/Deleting-Data-from-MHN


```
mongo mnemosyne
MongoDB shell version: 2.6.12
connecting to: mnemosyne
2017-07-03T17:01:07.042+0200 warning: Failed to connect to 127.0.0.1:27017, reason: errno:111 Connection refused
2017-07-03T17:01:07.042+0200 Error: couldn't connect to server 127.0.0.1:27017 (127.0.0.1), connection attempt failed at src/mongo/shell/mongo.js:146
exception: connect failed
```

**Comment by Waseem-farooqui** [comment] 2017-07-03 15:19
There are journals in mongodb I am talking about that `du -sh /var/lib/mongodb/*` also check the mongo service is it running ? `sudo service mongo status`

**Comment by br1877** [comment] 2017-07-03 15:42
```
du -sh /var/lib/mongodb/*
64M	/var/lib/mongodb/hpfeeds.0
16M	/var/lib/mongodb/hpfeeds.ns
4,0K	/var/lib/mongodb/journal
64M	/var/lib/mongodb/local.0
16M	/var/lib/mongodb/local.ns
65M	/var/lib/mongodb/mnemosyne.0
129M	/var/lib/mongodb/mnemosyne.1
2,0G	/var/lib/mongodb/mnemosyne.10
257M	/var/lib/mongodb/mnemosyne.2
513M	/var/lib/mongodb/mnemosyne.3
1,1G	/var/lib/mongodb/mnemosyne.4
2,0G	/var/lib/mongodb/mnemosyne.5
2,0G	/var/lib/mongodb/mnemosyne.6
2,0G	/var/lib/mongodb/mnemosyne.7
2,0G	/var/lib/mongodb/mnemosyne.8
2,0G	/var/lib/mongodb/mnemosyne.9
16M	/var/lib/mongodb/mnemosyne.ns
0	/var/lib/mongodb/mongod.lock
```
And the second command:

```
sudo service mongo status
mongo: unrecognized service
```

**Comment by Waseem-farooqui** [comment] 2017-07-04 05:43
Try `service mongod status` if if not running start the service.

**Comment by br1877** [comment] 2017-07-04 06:13
@Waseem-farooqui 

```
service mongod status
mongod stop/waiting
```
```
service mongod start
start: Rejected send message, 1 matched rules; type="method_call", sender=":1.18" (uid=1001 pid=2212 comm="start mongod ") interface="com.ubuntu.Upstart0_6.Job" member="Start" error name="(unset)" requested_reply="0" destination="com.ubuntu.Upstart" (uid=0 pid=1 comm="/sbin/init ")
```

**Comment by Waseem-farooqui** [comment] 2017-07-04 06:47
The problem is this:

`uid=1001`
That bit means that the user that contacted Upstart to perform the start action has the uid 1001 (not root, root is 0). That uid is usually assigned to the first non-system user. Something must be severely wrong with your usage of sudo, or sudo itself, because the command is not properly escalating to root.

You can see the same error with this command, for comparison (note the absence of sudo):

`sudo service mongod start`

**Comment by br1877** [comment] 2017-07-04 07:20
@Waseem-farooqui OK, the mongo service is already working. What next?

```
sudo service mongod start
mongod start/running, process 2389
```

**Comment by Waseem-farooqui** [comment] 2017-07-04 07:25
Restart the `supervisor` services I guess now the services will start running.

**Comment by br1877** [comment] 2017-07-04 07:26
I'm afraid that no:

```
supervisorctl stop all and start all
hpfeeds-broker: ERROR (abnormal termination)
mnemosyne: ERROR (abnormal termination)
mhn-celery-worker: ERROR (abnormal termination)
mhn-collector: ERROR (abnormal termination)
mhn-uwsgi: ERROR (abnormal termination)
mhn-celery-beat: started
geoloc: started
honeymap: started
```

**Closed** 2017-07-06 08:34 UTC
