### ISSUE TITLE
Cowire Errors

### ISSUE THREAD

**Issue by Jorrdannx** [threatstream/mhn#563] opened 2018-06-06 10:30 UTC
When running - sudo supervisorctl status

I get the following error - cowrie                           FATAL     Exited too quickly (process log may have details)

Cowrie error output log below.

raceback (most recent call last):
  File "/opt/cowrie/cowrie-env/bin/twistd", line 11, in <module>
    load_entry_point('Twisted==18.4.0', 'console_scripts', 'twistd')()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 31, in run
    app.run(runApp, ServerOptions)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 674, in run
    runApp(config)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    runner.run()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 381, in run
    self.application = self.createOrGetApplication()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 448, in createOrGetApplication
    ser = plg.makeService(self.config.subOptions)
  File "/opt/cowrie/twisted/plugins/cowrie_plugin.py", line 159, in makeService
    if CONFIG.getboolean(x, 'enabled') is False:
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 849, in getboolean
    **kwargs)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 822, in _get_conv
    return self._get(section, conv, option, **kwargs)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 814, in _get
    return conv(self.get(section, option, **kwargs))
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 803, in get
    raise NoOptionError(option, section)
backports.configparser.NoOptionError: No option 'enabled' in section: u'output_hpfeeds'
Traceback (most recent call last):
  File "/opt/cowrie/cowrie-env/bin/twistd", line 11, in <module>
    load_entry_point('Twisted==18.4.0', 'console_scripts', 'twistd')()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 31, in run
    app.run(runApp, ServerOptions)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 674, in run
    runApp(config)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    runner.run()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 381, in run
    self.application = self.createOrGetApplication()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 448, in createOrGetApplication
    ser = plg.makeService(self.config.subOptions)
  File "/opt/cowrie/twisted/plugins/cowrie_plugin.py", line 159, in makeService
    if CONFIG.getboolean(x, 'enabled') is False:
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 849, in getboolean
    **kwargs)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 822, in _get_conv
    return self._get(section, conv, option, **kwargs)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 814, in _get
    return conv(self.get(section, option, **kwargs))
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 803, in get
    raise NoOptionError(option, section)
backports.configparser.NoOptionError: No option 'enabled' in section: u'output_hpfeeds'
Traceback (most recent call last):
  File "/opt/cowrie/cowrie-env/bin/twistd", line 11, in <module>
    load_entry_point('Twisted==18.4.0', 'console_scripts', 'twistd')()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 31, in run
    app.run(runApp, ServerOptions)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 674, in run
    runApp(config)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    runner.run()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 381, in run
    self.application = self.createOrGetApplication()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 448, in createOrGetApplication
    ser = plg.makeService(self.config.subOptions)
  File "/opt/cowrie/twisted/plugins/cowrie_plugin.py", line 159, in makeService
    if CONFIG.getboolean(x, 'enabled') is False:
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 849, in getboolean
    **kwargs)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 822, in _get_conv
    return self._get(section, conv, option, **kwargs)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 814, in _get
    return conv(self.get(section, option, **kwargs))
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 803, in get
    raise NoOptionError(option, section)
backports.configparser.NoOptionError: No option 'enabled' in section: u'output_hpfeeds'
Traceback (most recent call last):
  File "/opt/cowrie/cowrie-env/bin/twistd", line 11, in <module>
    load_entry_point('Twisted==18.4.0', 'console_scripts', 'twistd')()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 31, in run
    app.run(runApp, ServerOptions)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 674, in run
    runApp(config)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    runner.run()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 381, in run
    self.application = self.createOrGetApplication()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 448, in createOrGetApplication
    ser = plg.makeService(self.config.subOptions)
  File "/opt/cowrie/twisted/plugins/cowrie_plugin.py", line 159, in makeService
    if CONFIG.getboolean(x, 'enabled') is False:
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 849, in getboolean
    **kwargs)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 822, in _get_conv
    return self._get(section, conv, option, **kwargs)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 814, in _get
    return conv(self.get(section, option, **kwargs))
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 803, in get
    raise NoOptionError(option, section)
backports.configparser.NoOptionError: No option 'enabled' in section: u'output_hpfeeds'
Traceback (most recent call last):
  File "/opt/cowrie/cowrie-env/bin/twistd", line 11, in <module>
    load_entry_point('Twisted==18.4.0', 'console_scripts', 'twistd')()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 31, in run
    app.run(runApp, ServerOptions)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 674, in run
    runApp(config)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    runner.run()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 381, in run
    self.application = self.createOrGetApplication()
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 448, in createOrGetApplication
    ser = plg.makeService(self.config.subOptions)
  File "/opt/cowrie/twisted/plugins/cowrie_plugin.py", line 159, in makeService
    if CONFIG.getboolean(x, 'enabled') is False:
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 849, in getboolean
    **kwargs)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 822, in _get_conv
    return self._get(section, conv, option, **kwargs)
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 814, in _get
    return conv(self.get(section, option, **kwargs))
  File "/opt/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 803, in get
    raise NoOptionError(option, section)
backports.configparser.NoOptionError: No option 'enabled' in section: u'output_hpfeeds'

Any help appreciated.

**Comment by kyle-schleich** [comment] 2018-06-06 11:30
The problem is that in cowrie.cfg hpfeeds is not enabled in the script be default. The option is towards the bottom of the config.

This is also fixed in #555

**Comment by Jorrdannx** [comment] 2018-06-06 13:23
Works perfect, thanks

**Comment by Jorrdannx** [comment] 2018-06-07 07:12
So after editing the config with the changes. Attacks started coming into the ui within 30 seconds but you'll find a lot of it is just scans, no attacks.

**Comment by coonsmatthew** [comment] 2018-06-08 15:33
I was also having this issue. @d1str0 Can we get this merged, provided there are no conflicts? 

Thanks.

**Comment by d1str0** [comment] 2018-08-05 02:00
All merged. :P

**Closed by d1str0** 2018-08-05 02:00 UTC
Labels: bug, installation, troubleshooting
