### ISSUE TITLE
Add support for mailoney honeypot.

### ISSUE THREAD

**Issue by dpicollege** [threatstream/mhn#464] opened 2017-10-10 15:09 UTC
Hello,
Please add mailoney (smtp honeypot)

**Comment by d1str0** [comment] 2017-10-10 19:50
https://github.com/awhitehatter/mailoney

**Comment by dpicollege** [comment] 2017-10-11 06:54
yes that's it.

**Comment by d1str0** [comment] 2017-10-19 23:39
Duplicate of #113

**Closed by d1str0** 2017-10-19 23:39 UTC
Labels: enhancement
