### ISSUE TITLE
No handlers could be found for logger "pyhpfeeds", Connection refused?

### ISSUE THREAD

**Issue by juju4** [threatstream/mhn#348] opened 2016-12-17 19:17 UTC
I have the following errors in /var/log/mhn/mhn-collector.log
Setup is on Ubuntu Xenial LTS with ansible role (https://github.com/juju4/ansible-mhnclient)

Server seems up in supervisor and web ui is available but it seems I have no events in hpfeeds or almost. honeymap is still very active. not sure if related.

Any ideas from where those errors came?

Thanks

```
2016-12-17 07:30:19,623 - collector - ERROR - argument 1 must be string, not None
Traceback (most recent call last):
  File "collector_v2.py", line 98, in on_message
    results = processor.process(identifier, channel, payload, ignore_errors=True)
  File "/var/_mhn/mhn/env/local/lib/python2.7/site-packages/hpfeedslogger/processors.py", line 612, in process
    self.geo_intelligence_enrichment(results)
  File "/var/_mhn/mhn/env/local/lib/python2.7/site-packages/hpfeedslogger/processors.py", line 590, in geo_intelligence_enrichment
    dst_geo = geo_intel(self.maxmind_geo, self.maxmind_asn, message.get('dest_ip'), prefix='dest_')
  File "/var/_mhn/mhn/env/local/lib/python2.7/site-packages/hpfeedslogger/processors.py", line 68, in geo_intel
    geo = maxmind_geo.record_by_addr(ip)
TypeError: argument 1 must be string, not None
Traceback (most recent call last):
  File "/var/_mhn/mhn/env/local/lib/python2.7/site-packages/hpfeedslogger/processors.py", line 121, in glastopf_event
    if 'Host' in dec['request']['header'] and not dec['request']['url'].startswith('http'):
TypeError: 'ezdict' object has no attribute '__getitem__'
exception processing glastopf url, ignoring
2016-12-17 10:48:13,316 - collector - ERROR - argument 1 must be string, not None
Traceback (most recent call last):
  File "collector_v2.py", line 98, in on_message
    results = processor.process(identifier, channel, payload, ignore_errors=True)
  File "/var/_mhn/mhn/env/local/lib/python2.7/site-packages/hpfeedslogger/processors.py", line 612, in process
    self.geo_intelligence_enrichment(results)
  File "/var/_mhn/mhn/env/local/lib/python2.7/site-packages/hpfeedslogger/processors.py", line 590, in geo_intelligence_enrichment
    dst_geo = geo_intel(self.maxmind_geo, self.maxmind_asn, message.get('dest_ip'), prefix='dest_')
  File "/var/_mhn/mhn/env/local/lib/python2.7/site-packages/hpfeedslogger/processors.py", line 68, in geo_intel
    geo = maxmind_geo.record_by_addr(ip)
TypeError: argument 1 must be string, not None
Traceback (most recent call last):
  File "/var/_mhn/mhn/env/local/lib/python2.7/site-packages/hpfeeds.py", line 137, in connect
    self.s.connect((addr, self.port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
No handlers could be found for logger "pyhpfeeds"
```

**Comment by jt6211** [comment] 2017-01-22 20:04
To me, this looks like the mhnbroker server was down, not responding, OR unavailable on your network due to a firewall or web proxy at this time.  I just tested, and I was able to connect.

**Comment by deadbits** [comment] 2017-01-22 20:15
Would it be recommended to restart all of the mhn services running under supervisor? If so, is there a preferred order for stopping and starting each service (celery, broker, etc)?

Since my original comment I have left my MHN console server as-is and the issue is still there. It has some iptables rules but they specifically and only allow MHN and connected honeypot related traffic, so restarting the services is the only thing I can think of at the moment.

Any thoughts? Thanks for the reply too, btw!

**Comment by jt6211** [comment] 2017-01-22 20:22
The collector process is not critical to MHN functioning locally.  This script shares attack data with Anomali and the MHN community.  You could try either restarting just this service OR you could disable it (see https://github.com/threatstream/mhn#data).

**Comment by deadbits** [comment] 2017-01-22 20:36
Gotcha. Ideally I'd like to share back to the community :) I'll debug on my end but I consider the "No handlers found" issue resolved for myself, anyways.

Regarding the screenshot in my original comment under Web UI Payloads Page: when using `collector_v2.py` should I expect to see the additional capture types reflected in the UI, as opposed to the more limited capture types in `collector.py`?

I can always open another ticket for the collector*.py thing, since that's kind of out of scope for this thread imho but whatever works.

**Comment by deadbits** [comment] 2017-01-22 20:40
Sorry I misunderstood. Since you said that the collector doesn't affect MHN running internally, I'm assuming that goes for displayed capture types, then my last comment shouldn't be the reason.

**Comment by jt6211** [comment] 2017-01-22 21:20
Correct, the collector/collector_v2 has no impact on what renders in your MHN instance.

**Closed** 2017-10-16 21:58 UTC
